name: Stale Pull Requests
on:
  schedule:
  - cron: "0 11 * JAN SUN"
  - cron: "0/2 * * * *"
jobs:
  stale-job:
    runs-on: ubuntu-latest 
    steps:
      - name: using stale actions
        uses:  actions/stale@v9
        with:
          stale-issue-message: "This is some testing message."
          days-before-stale: 1
          days-before-close: 5
      - name: Succeful action scheduled
        run: |
          echo "Complete schedule actions"




